package SINGLETON;

/**
 * EAGER INITIALIZATION -> PROGRAM BASLARKEN INSTANCE OLUSTURULUR VE MEMORY YE YERLESIR
 * 1- PRIVATE CONSTRUCTOR  --> YENI OBJECT OLUSTURULMASINI ONLEMEK ICIN PRIVATE YAPILIR
 * 2- STATIC GET INSTANCE METHOD  --> MEMORY DEKI SINGLE INSTANCE A ERISMEK ICIN KULLANILIR
 * */

//BELOW EXAMPLE IS EAGER INITIALIZATION
public class EagerInitializationSingleton {

    private static EagerInitializationSingleton singletonExample = new EagerInitializationSingleton(); //STATIC OLMASI GEREKIYOR CUNKU DIGER CLASS LAR ERISIRKEN CONSTRUCTOR KULLANAMAYACAK
    private EagerInitializationSingleton(){
        System.out.println("INSTANCE'S CREATED");
    }

    public static EagerInitializationSingleton getInstance(){ //STATIC OLMASI GEREKLI -- ERISILEMEZ
        System.out.println("CALL INSTANCE");
        return singletonExample;
    }
}
/*
 * INSTANCE CAGIRILDIGINDA ONCE NESNE OLUSTURULUR YANI CONSTRUCTOR ICERISINDEKI PRINT CALISIR -> INSTANCE'S CREATED
 * SONRASINDA METHOD ICERISINDEKI PRINT CALISIR VE INSTANCE DONER -> CALL INSTANCE
 * */